---
- name: Include OS-specific variables.
  include_vars: no-raspbian.yml
  when: ansible_lsb.id != 'Raspbian'

- name: Supervisor | pirest-sense-hat config
  template:
    src: templates/supervisor.pirest_sense_hat.conf.j2
    dest: "/etc/supervisor/conf.d/{{rpirest_app_name}}.conf"
    owner: "{{ rpirest_app_user }}"
    group: "{{ rpirest_app_user }}"
    mode: 0664
    force: yes
  notify: reread supervisor
#- name: Ensure nginx is started and enabled to start at boot.
#service: name=nginx state=started enabled=yes

- name: Django | Copy Django's settings_local for APP {{ rpirest_app_name }}
  template:
    src: templates/settings_local.py.j2
    dest: "{{ rpirest_app_path }}/{{rpirest_app_name}}/settings_local.py"
    owner: "{{ rpirest_app_user }}"
    group: "{{ rpirest_app_group }}"
    mode: 0664
    force: yes
  notify: restart pirest-sense-hat

- name: Create log directory for {{ rpirest_app_name }}
  file:
    path: "{{ rpirest_app_dir_logs }}"
    owner: "{{ rpirest_app_user }}"
    group: "{{ rpirest_app_group }}"
    state: directory
    mode: 0755

- name: Django | Checking Static files for {{ rpirest_app_name }}
  file:
    path: "{{ rpirest_app_statics }}"
    state: directory
    mode: 0644
  notify: django collect_static

