- name: Installing packages
  action: apt name={{ item }} state=present
  with_items:
    - git
    - python3-pip
    - vim
    - supervisor
    - nginx
    - python3-numpy
    - libopenjp2-7
    - redis-server 
  tags:
    - installation

- name: Installing sense-hat package
  action: apt name=python3-sense-hat state=present
  when: ansible_lsb.id == "Raspbian"

- name: Create APP Directory {{ rpirest_app_name }}
  file:
    path: "{{ rpirest_app_path }}"
    owner: "{{ rpirest_app_user }}"
    group: "{{ rpirest_app_group }}"
    state: directory
    mode: 0755

- name: Copying Pip3 install requirements
  copy:
        src: "{{ role_path }}/files/requirements.txt"
        dest: "{{rpirest_app_path}}/requirements.txt"

- name: Executing pip3 -r requirements.txt
  pip:
    requirements: "{{ rpirest_app_path }}/requirements.txt"
    executable: pip3

- name: Syncronyzing rpirest code from disk
  synchronize: src="{{ rpirest_app_src_path }}/" dest="{{ rpirest_app_path }}"
  when: rpirest_sync_from_git == False
  tags:
    - app_code
  notify:
    - django migrate
    - django collect_static
    - restart pirest-sense-hat
    - django installtasks


