- name: Installing packages
  action: apt name={{ item }} state=present
  with_items:
    - git
    - python3-pip
    - vim
    - supervisor
    - nginx
    - python3-numpy
  tags:
    - installation


- name: Installing sense-hat package
  action: apt name=sense-hat state=present
  when: ansible_lsb.id == "Raspbian"

- name: Create APP Directory {{ app_name }}
  file:
    path: "{{ app_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    state: directory
    mode: 0755

- name: Syncronyzing rpirest code
  synchronize: src="{{ app_src }}" dest="{{ app_path }}"
  tags:
    - app_code
  notify:
    - django migrate
    - django collect_static
    - restart pirest-sense-hat
    - django installtasks

#- git:
#      repo: ssh://git@gitlab.com:jregueirar/rpirest.git
#      dest: {{ app_path }}
#      version: v.401
#notify:
#  - django migrate
#  - django collect_static
#  - restart pirest-sense-hat
#  #  - django installtasks

- name: Executing pip3 -r requirements.txt
  pip:
    requirements: "{{ app_path }}/requirements.txt"
    executable: pip3


