---
#- debug: var=ansible_os_family

#- debug:
#    msg: "Role dir is {{ role_path }}"

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags:
    - installation

- include: install_dht_library.yml
  tags:
    - installation

- include: mpd.yml
  tags: 
    - installation
    - mpd

- include: configure.yml
  tags: 
    - configuration

- include: nginx.yml
  tags:
    - nginx

- include: async_tasks.yml
  tags: 
    - async_tasks

