---
- name: restart pirest-sense-hat
  command: supervisorctl restart {{rpirest_app_name}}

- name: reread supervisor
  command: "supervisorctl update"

- name: django collect_static
  command: python3 manage.py collectstatic --noinput
  args:
    chdir: "{{ rpirest_app_path }}"
  become: true

- name: django installtasks
  command: python3 manage.py installtasks
  args:
    chdir: "{{ rpirest_app_path }}"
  become: true

- name: django migrate
  command: python3 manage.py migrate
  args:
    chdir: "{{ rpirest_app_path }}"

- name: restart nginx
  service: name=nginx state=restarted
